In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("food_delivery_raw.csv")

In [3]:
df = df_raw

In [4]:
df

,order_id,restaurant,cuisine,order_amount,delivery_minutes,order_date,payment_mode,delivery_rating,customer_city
0,7001,Spice Villa,Indian,450.0,32.0,2024-03-01,card,4.5,Pune
1,7002,burger barn,American,320.0,25.0,2024-03-01,Cash,4.0,mumbai
2,7003,Spice Villa,indian,450.0,32.0,2024-03-01,Card,4.5,Pune
3,7004,Sushi Central,Japanese,890.0,NaN,03/02/2024,UPI,4.8,Delhi
4,7005,Pasta Palace,Italian,610.0,40.0,2024-03-02,cash,NaN,Pune
5,7006,Burger Barn,american,290.0,22.0,2024-03-03,Card,3.9,Mumbai
6,7007,Curry House,Indian,530.0,-10.0,2024-03-03,upi,4.2,delhi
7,7008,Sushi Central,japanese,910.0,55.0,2024-03-04,Card,4.7,Delhi
8,7009,Pasta Palace,Italian,610.0,40.0,2024-03-02,Cash,4.1,Pune
9,7010,Taco Town,Mexican,275.0,28.0,2024-03-04,UPI,4.3,Bangalore
10,7011,Curry House,indian,540.0,35.0,04-03-2024,Cash,4.0,Delhi
11,7012,Burger Barn,American,305.0,850.0,2024-03-05,card,3.8,mumbai
12,7013,Taco Town,mexican,NaN,30.0,2024-03-05,Cash,4.5,bangalore
13,7014,Spice Villa,Indian,470.0,38.0,2024-03-06,UPI,NaN,Pune
14,7015,Sushi Central,Japanese,-890.0,45.0,2024-03-06,Card,4.6,Delhi
15,7016,Pasta Palace,italian,625.0,42.0,invalid_date,Cash,4.2,Pune
16,7017,Curry House,Indian,550.0,33.0,2024-03-07,upi,4.1,Delhi
17,7018,Taco Town,Mexican,280.0,26.0,2024-03-07,Card,4.4,Bangalore
18,7019,Burger Barn,American,310.0,24.0,2024-03-08,cash,3.7,Mumbai
19,7020,Spice Villa,indian,460.0,36.0,2024-03-08,UPI,4.5,pune

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          20 non-null     int64
 1   restaurant        20 non-null     object
 2   cuisine           20 non-null     object
 3   order_amount      19 non-null     float64
 4   delivery_minutes  19 non-null     float64
 5   order_date        20 non-null     object
 6   payment_mode      20 non-null     object
 7   delivery_rating   18 non-null     float64
 8   customer_city     20 non-null     object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.5+ KB

In [6]:
df.describe()

         order_id  order_amount  delivery_minutes  delivery_rating
count    20.00000     19.000000         19.000000        18.000000
mean   7010.50000    420.263158         74.894737         4.266667
std       5.91608    367.685983        188.146779         0.316228
min    7001.00000   -890.000000        -10.000000         3.700000
25%    7005.75000    307.500000         27.000000         4.025000
50%    7010.50000    460.000000         33.000000         4.250000
75%    7015.25000    580.000000         40.000000         4.500000
max    7020.00000    910.000000        850.000000         4.800000

In [8]:
df["restaurant"] = df["restaurant"].str.strip().str.lower()

In [10]:
df["cuisine"] = df["cuisine"].str.strip().str.lower()

In [12]:
df["payment_mode"] = df["payment_mode"].str.strip().str.lower()

In [14]:
df["customer_city"] = df["customer_city"].str.strip().str.lower()

In [15]:
df

,order_id,restaurant,cuisine,order_amount,delivery_minutes,order_date,payment_mode,delivery_rating,customer_city
0,7001,spice villa,indian,450.0,32.0,2024-03-01,card,4.5,pune
1,7002,burger barn,american,320.0,25.0,2024-03-01,cash,4.0,mumbai
2,7003,spice villa,indian,450.0,32.0,2024-03-01,card,4.5,pune
3,7004,sushi central,japanese,890.0,NaN,03/02/2024,upi,4.8,delhi
4,7005,pasta palace,italian,610.0,40.0,2024-03-02,cash,NaN,pune
5,7006,burger barn,american,290.0,22.0,2024-03-03,card,3.9,mumbai
6,7007,curry house,indian,530.0,-10.0,2024-03-03,upi,4.2,delhi
7,7008,sushi central,japanese,910.0,55.0,2024-03-04,card,4.7,delhi
8,7009,pasta palace,italian,610.0,40.0,2024-03-02,cash,4.1,pune
9,7010,taco town,mexican,275.0,28.0,2024-03-04,upi,4.3,bangalore
10,7011,curry house,indian,540.0,35.0,04-03-2024,cash,4.0,delhi
11,7012,burger barn,american,305.0,850.0,2024-03-05,card,3.8,mumbai
12,7013,taco town,mexican,NaN,30.0,2024-03-05,cash,4.5,bangalore
13,7014,spice villa,indian,470.0,38.0,2024-03-06,upi,NaN,pune
14,7015,sushi central,japanese,-890.0,45.0,2024-03-06,card,4.6,delhi
15,7016,pasta palace,italian,625.0,42.0,invalid_date,cash,4.2,pune
16,7017,curry house,indian,550.0,33.0,2024-03-07,upi,4.1,delhi
17,7018,taco town,mexican,280.0,26.0,2024-03-07,card,4.4,bangalore
18,7019,burger barn,american,310.0,24.0,2024-03-08,cash,3.7,mumbai
19,7020,spice villa,indian,460.0,36.0,2024-03-08,upi,4.5,pune

In [20]:
df = df.drop_duplicates(df.columns.drop(["order_id","delivery_rating"]))

In [37]:
df

,order_id,restaurant,cuisine,order_amount,delivery_minutes,order_date,payment_mode,delivery_rating,customer_city
0,7001,spice villa,indian,450.0,32.000000,2024-03-01,card,4.5,pune
1,7002,burger barn,american,320.0,25.000000,2024-03-01,cash,4.0,mumbai
3,7004,sushi central,japanese,890.0,34.066667,2024-03-02,upi,4.8,delhi
4,7005,pasta palace,italian,610.0,40.000000,2024-03-02,cash,0.0,pune
5,7006,burger barn,american,290.0,22.000000,2024-03-03,card,3.9,mumbai
6,7007,curry house,indian,530.0,34.066667,2024-03-03,upi,4.2,delhi
7,7008,sushi central,japanese,910.0,55.000000,2024-03-04,card,4.7,delhi
9,7010,taco town,mexican,275.0,28.000000,2024-03-04,upi,4.3,bangalore
10,7011,curry house,indian,540.0,35.000000,2024-04-03,cash,4.0,delhi
11,7012,burger barn,american,305.0,34.066667,2024-03-05,card,3.8,mumbai
12,7013,taco town,mexican,NaN,30.000000,2024-03-05,cash,4.5,bangalore
13,7014,spice villa,indian,470.0,38.000000,2024-03-06,upi,0.0,pune
14,7015,sushi central,japanese,NaN,45.000000,2024-03-06,card,4.6,delhi
15,7016,pasta palace,italian,625.0,42.000000,NaT,cash,4.2,pune
16,7017,curry house,indian,550.0,33.000000,2024-03-07,upi,4.1,delhi
17,7018,taco town,mexican,280.0,26.000000,2024-03-07,card,4.4,bangalore
18,7019,burger barn,american,310.0,24.000000,2024-03-08,cash,3.7,mumbai
19,7020,spice villa,indian,460.0,36.000000,2024-03-08,upi,4.5,pune

In [22]:
import numpy as np

In [23]:
df.loc[df["order_amount"] < 0 , "order_amount"] = np.nan

In [25]:
df.loc[ (df["delivery_minutes"] > 120) | (df["delivery_minutes"] < 0 ) , "delivery_minutes" ]= np.nan

In [27]:
df["delivery_rating"] = df["delivery_rating"].fillna(0)

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_11880/3627626801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_rating"] = df["delivery_rating"].fillna(0)

In [29]:
df["order_date"] = pd.to_datetime(df["order_date"] , format="mixed" , errors="coerce")

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_11880/2167051834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["order_date"] = pd.to_datetime(df["order_date"] , format="mixed" , errors="coerce")

In [31]:
df["order_date"].isnull()

0     False
1     False
3     False
4     False
5     False
6     False
7     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
Name: order_date, dtype: bool

In [34]:
df_deliver_minutes = df["delivery_minutes"]

In [36]:
df["delivery_minutes"] = df_deliver_minutes.fillna(df_deliver_minutes.mean())

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_11880/1618434107.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_minutes"] = df_deliver_minutes.fillna(df_deliver_minutes.mean())

In [41]:
df["delivery_minutes"] = df["delivery_minutes"].astype(int)

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_11880/2530053674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["delivery_minutes"] = df["delivery_minutes"].astype(int)

In [44]:
df

,order_id,restaurant,cuisine,order_amount,delivery_minutes,order_date,payment_mode,delivery_rating,customer_city
0,7001,spice villa,indian,450.0,32,2024-03-01,card,4.5,pune
1,7002,burger barn,american,320.0,25,2024-03-01,cash,4.0,mumbai
3,7004,sushi central,japanese,890.0,34,2024-03-02,upi,4.8,delhi
4,7005,pasta palace,italian,610.0,40,2024-03-02,cash,0.0,pune
5,7006,burger barn,american,290.0,22,2024-03-03,card,3.9,mumbai
6,7007,curry house,indian,530.0,34,2024-03-03,upi,4.2,delhi
7,7008,sushi central,japanese,910.0,55,2024-03-04,card,4.7,delhi
9,7010,taco town,mexican,275.0,28,2024-03-04,upi,4.3,bangalore
10,7011,curry house,indian,540.0,35,2024-04-03,cash,4.0,delhi
11,7012,burger barn,american,305.0,34,2024-03-05,card,3.8,mumbai
13,7014,spice villa,indian,470.0,38,2024-03-06,upi,0.0,pune
16,7017,curry house,indian,550.0,33,2024-03-07,upi,4.1,delhi
17,7018,taco town,mexican,280.0,26,2024-03-07,card,4.4,bangalore
18,7019,burger barn,american,310.0,24,2024-03-08,cash,3.7,mumbai
19,7020,spice villa,indian,460.0,36,2024-03-08,upi,4.5,pune

In [43]:
df.dropna(inplace=True)

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_11880/1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [47]:
df.reset_index(drop=True , inplace=True)

,order_id,restaurant,cuisine,order_amount,delivery_minutes,order_date,payment_mode,delivery_rating,customer_city
0,7001,spice villa,indian,450.0,32,2024-03-01,card,4.5,pune
1,7002,burger barn,american,320.0,25,2024-03-01,cash,4.0,mumbai
2,7004,sushi central,japanese,890.0,34,2024-03-02,upi,4.8,delhi
3,7005,pasta palace,italian,610.0,40,2024-03-02,cash,0.0,pune
4,7006,burger barn,american,290.0,22,2024-03-03,card,3.9,mumbai
5,7007,curry house,indian,530.0,34,2024-03-03,upi,4.2,delhi
6,7008,sushi central,japanese,910.0,55,2024-03-04,card,4.7,delhi
7,7010,taco town,mexican,275.0,28,2024-03-04,upi,4.3,bangalore
8,7011,curry house,indian,540.0,35,2024-04-03,cash,4.0,delhi
9,7012,burger barn,american,305.0,34,2024-03-05,card,3.8,mumbai
10,7014,spice villa,indian,470.0,38,2024-03-06,upi,0.0,pune
11,7017,curry house,indian,550.0,33,2024-03-07,upi,4.1,delhi
12,7018,taco town,mexican,280.0,26,2024-03-07,card,4.4,bangalore
13,7019,burger barn,american,310.0,24,2024-03-08,cash,3.7,mumbai
14,7020,spice villa,indian,460.0,36,2024-03-08,upi,4.5,pune