In [2]:
import pandas as pd

In [18]:
df = pd.read_csv("1_missing_values.csv")
df

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
1           2    Diya  Science    NaN        88.0
2           3   Kabir     Math   65.0         NaN
3           4   Meera  English    NaN        79.0
4           5   Rohan  Science   54.0        95.0
5           6    Isha     Math    NaN         NaN
6           7  Aditya  English   88.0        84.0
7           8   Priya  Science   90.0         NaN
8           9  Vivaan     Math   72.0        90.0
9          10    Sara  English    NaN        81.0

In [4]:
df.isnull().sum() #checking missing values

student_id    0
name          0
subject       0
score         4
attendance    3
dtype: int64

In [11]:
df_cleaned_score = df.dropna(subset=["score","attendance"])

In [9]:
df_cleaned_attendance = df.dropna(subset=["attendance"])

In [12]:
df_cleaned_score

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
4           5   Rohan  Science   54.0        95.0
6           7  Aditya  English   88.0        84.0
8           9  Vivaan     Math   72.0        90.0

In [13]:
df

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
1           2    Diya  Science    NaN        88.0
2           3   Kabir     Math   65.0         NaN
3           4   Meera  English    NaN        79.0
4           5   Rohan  Science   54.0        95.0
5           6    Isha     Math    NaN         NaN
6           7  Aditya  English   88.0        84.0
7           8   Priya  Science   90.0         NaN
8           9  Vivaan     Math   72.0        90.0
9          10    Sara  English    NaN        81.0

In [14]:
df["attendance"] = df["attendance"].fillna(df["attendance"].mean())

In [16]:
df["score"] = df["score"].fillna(df["score"].mean())

In [20]:
df_ffill = df["score"].ffill()

In [21]:
df_ffill

0    78.0
1    78.0
2    65.0
3    65.0
4    54.0
5    54.0
6    88.0
7    90.0
8    72.0
9    72.0
Name: score, dtype: float64

In [22]:
df_bfill = df["score"].bfill()

In [23]:
df_bfill

0    78.0
1    65.0
2    65.0
3    54.0
4    54.0
5    88.0
6    88.0
7    90.0
8    72.0
9     NaN
Name: score, dtype: float64