In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("2_duplicates_strings.csv")
df

   cust_id            name       city                   email
0      201     Rahul Verma      Delhi   rahul.verma@email.com
1      202    ANITA SHARMA     mumbai  anita.sharma@email.com
2      203     Rahul Verma      Delhi   rahul.verma@email.com
3      204     Suresh Nair  Bangalore   suresh.nair@email.com
4      205    anita sharma     Mumbai  anita.sharma@email.com
5      206     Karan Mehta      DELHI   karan.mehta@email.com
6      207      Pooja Iyer  bangalore    pooja.iyer@email.com
7      208     Suresh Nair  Bangalore   suresh.nair@email.com
8      209     Neha Kapoor    Chennai   neha.kapoor@email.com
9      210     Karan Mehta      Delhi   karan.mehta@email.com

In [3]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [8]:
df["name"] = df["name"].str.strip().str.lower()

In [10]:
df["city"] = df["city"].str.strip().str.lower()

In [11]:
df

   cust_id          name       city                   email
0      201   rahul verma      delhi   rahul.verma@email.com
1      202  anita sharma     mumbai  anita.sharma@email.com
2      203   rahul verma      delhi   rahul.verma@email.com
3      204   suresh nair  bangalore   suresh.nair@email.com
4      205  anita sharma     mumbai  anita.sharma@email.com
5      206   karan mehta      delhi   karan.mehta@email.com
6      207    pooja iyer  bangalore    pooja.iyer@email.com
7      208   suresh nair  bangalore   suresh.nair@email.com
8      209   neha kapoor    chennai   neha.kapoor@email.com
9      210   karan mehta      delhi   karan.mehta@email.com

In [14]:
df.drop_duplicates(subset=["name","city"])

   cust_id          name       city                   email
0      201   rahul verma      delhi   rahul.verma@email.com
1      202  anita sharma     mumbai  anita.sharma@email.com
3      204   suresh nair  bangalore   suresh.nair@email.com
5      206   karan mehta      delhi   karan.mehta@email.com
6      207    pooja iyer  bangalore    pooja.iyer@email.com
8      209   neha kapoor    chennai   neha.kapoor@email.com

In [15]:
df["city"].str.contains("delhi" , case=False)

0     True
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: city, dtype: bool

In [17]:
df["email"].str.split("@")

0     [rahul.verma, email.com]
1    [anita.sharma, email.com]
2     [rahul.verma, email.com]
3     [suresh.nair, email.com]
4    [anita.sharma, email.com]
5     [karan.mehta, email.com]
6      [pooja.iyer, email.com]
7     [suresh.nair, email.com]
8     [neha.kapoor, email.com]
9     [karan.mehta, email.com]
Name: email, dtype: object