In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("streaming_viewership_raw.csv")

In [4]:
df_copy = df

In [10]:
sorted_df = df_copy.sort_values("user_age" , ascending=False)

In [14]:
sorted_df.reset_index(drop=True , inplace=True)

In [15]:
sorted_df

,view_id,user_name,show_title,genre,watch_minutes,user_rating,watch_date,device,plan,user_age
0,9013,Ibrahim Sait,Comedy Hour,Comedy,18.0,3.5,invalid_date,Mobile,basic,250.0
1,9007,Meera Iyer,Ocean Deep,Documentary,90.0,4.7,03-02-2024,TV,premium,45.0
2,9015,Vivek Rao,The Last Case,Thriller,70.0,NaN,2024-02-06,Mobile,premium,41.0
3,9011,Divya Nair,The Last Case,thriller,65.0,4.6,2024-02-04,TV,basic,38.0
4,9019,Rahul Sen,Space Odyssey,sci-fi,58.0,4.4,2024-02-07,Mobile,premium,35.0
5,9012,Farah Sheikh,Ocean Deep,Documentary,99999.0,4.8,2024-02-05,Tablet,Premium,33.0
6,9009,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0
7,9002,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0
8,9018,Ayesha Khan,Comedy Hour,Comedy,22.0,3.9,2024-02-07,Tablet,Basic,30.0
9,9004,Leo Fernandes,Space Odyssey,Sci-Fi,NaN,4.9,02/02/2024,tv,basic,29.0
10,9020,Anita Roy,Midnight Trail,thriller,48.0,4.1,2024-02-08,TV,basic,28.0
11,9008,Sana Ali,Space Odyssey,sci-fi,55.0,4.2,2024-02-03,Mobile,Basic,27.0
12,9014,Neha Joshi,Space Odyssey,Sci-Fi,50.0,4.3,2024-02-05,tv,Basic,26.0
13,9003,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0
14,9001,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0
15,9010,Karan Bose,Midnight Trail,Thriller,-15.0,3.0,2024-02-04,Mobile,premium,22.0
16,9017,Karan Bose,Midnight Trail,Thriller,42.0,3.0,2024-02-04,Mobile,premium,22.0
17,9006,Rohan Kapoor,Comedy Hour,comedy,25.0,4.0,2024-02-03,Tablet,basic,19.0
18,9005,Priya Das,The Last Case,Thriller,60.0,NaN,2024-02-02,Mobile,PREMIUM,NaN
19,9016,Tanya Grover,Ocean Deep,documentary,85.0,4.9,2024-02-06,TV,basic,NaN

In [18]:
sorted_df["rank"] = sorted_df["user_rating"].rank()

In [19]:
sorted_df

,view_id,user_name,show_title,genre,watch_minutes,user_rating,watch_date,device,plan,user_age,rank
0,9013,Ibrahim Sait,Comedy Hour,Comedy,18.0,3.5,invalid_date,Mobile,basic,250.0,3.0
1,9007,Meera Iyer,Ocean Deep,Documentary,90.0,4.7,03-02-2024,TV,premium,45.0,15.0
2,9015,Vivek Rao,The Last Case,Thriller,70.0,NaN,2024-02-06,Mobile,premium,41.0,NaN
3,9011,Divya Nair,The Last Case,thriller,65.0,4.6,2024-02-04,TV,basic,38.0,14.0
4,9019,Rahul Sen,Space Odyssey,sci-fi,58.0,4.4,2024-02-07,Mobile,premium,35.0,11.0
5,9012,Farah Sheikh,Ocean Deep,Documentary,99999.0,4.8,2024-02-05,Tablet,Premium,33.0,16.0
6,9009,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0,4.5
7,9002,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0,4.5
8,9018,Ayesha Khan,Comedy Hour,Comedy,22.0,3.9,2024-02-07,Tablet,Basic,30.0,6.0
9,9004,Leo Fernandes,Space Odyssey,Sci-Fi,NaN,4.9,02/02/2024,tv,basic,29.0,17.5
10,9020,Anita Roy,Midnight Trail,thriller,48.0,4.1,2024-02-08,TV,basic,28.0,8.0
11,9008,Sana Ali,Space Odyssey,sci-fi,55.0,4.2,2024-02-03,Mobile,Basic,27.0,9.0
12,9014,Neha Joshi,Space Odyssey,Sci-Fi,50.0,4.3,2024-02-05,tv,Basic,26.0,10.0
13,9003,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0,12.5
14,9001,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0,12.5
15,9010,Karan Bose,Midnight Trail,Thriller,-15.0,3.0,2024-02-04,Mobile,premium,22.0,1.5
16,9017,Karan Bose,Midnight Trail,Thriller,42.0,3.0,2024-02-04,Mobile,premium,22.0,1.5
17,9006,Rohan Kapoor,Comedy Hour,comedy,25.0,4.0,2024-02-03,Tablet,basic,19.0,7.0
18,9005,Priya Das,The Last Case,Thriller,60.0,NaN,2024-02-02,Mobile,PREMIUM,NaN,NaN
19,9016,Tanya Grover,Ocean Deep,documentary,85.0,4.9,2024-02-06,TV,basic,NaN,17.5

In [20]:
sorted_df["rank"] = sorted_df["user_rating"].rank(method="dense")

In [21]:
sorted_df

,view_id,user_name,show_title,genre,watch_minutes,user_rating,watch_date,device,plan,user_age,rank
0,9013,Ibrahim Sait,Comedy Hour,Comedy,18.0,3.5,invalid_date,Mobile,basic,250.0,2.0
1,9007,Meera Iyer,Ocean Deep,Documentary,90.0,4.7,03-02-2024,TV,premium,45.0,12.0
2,9015,Vivek Rao,The Last Case,Thriller,70.0,NaN,2024-02-06,Mobile,premium,41.0,NaN
3,9011,Divya Nair,The Last Case,thriller,65.0,4.6,2024-02-04,TV,basic,38.0,11.0
4,9019,Rahul Sen,Space Odyssey,sci-fi,58.0,4.4,2024-02-07,Mobile,premium,35.0,9.0
5,9012,Farah Sheikh,Ocean Deep,Documentary,99999.0,4.8,2024-02-05,Tablet,Premium,33.0,13.0
6,9009,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0,3.0
7,9002,arjun mehta,Comedy Hour,Comedy,20.0,3.8,2024-02-01,TV,Premium,31.0,3.0
8,9018,Ayesha Khan,Comedy Hour,Comedy,22.0,3.9,2024-02-07,Tablet,Basic,30.0,4.0
9,9004,Leo Fernandes,Space Odyssey,Sci-Fi,NaN,4.9,02/02/2024,tv,basic,29.0,14.0
10,9020,Anita Roy,Midnight Trail,thriller,48.0,4.1,2024-02-08,TV,basic,28.0,6.0
11,9008,Sana Ali,Space Odyssey,sci-fi,55.0,4.2,2024-02-03,Mobile,Basic,27.0,7.0
12,9014,Neha Joshi,Space Odyssey,Sci-Fi,50.0,4.3,2024-02-05,tv,Basic,26.0,8.0
13,9003,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0,10.0
14,9001,Zara Khan,Midnight Trail,Thriller,45.0,4.5,2024-02-01,Mobile,premium,24.0,10.0
15,9010,Karan Bose,Midnight Trail,Thriller,-15.0,3.0,2024-02-04,Mobile,premium,22.0,1.0
16,9017,Karan Bose,Midnight Trail,Thriller,42.0,3.0,2024-02-04,Mobile,premium,22.0,1.0
17,9006,Rohan Kapoor,Comedy Hour,comedy,25.0,4.0,2024-02-03,Tablet,basic,19.0,5.0
18,9005,Priya Das,The Last Case,Thriller,60.0,NaN,2024-02-02,Mobile,PREMIUM,NaN,NaN
19,9016,Tanya Grover,Ocean Deep,documentary,85.0,4.9,2024-02-06,TV,basic,NaN,14.0