In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("3_types_apply_map.csv")

In [3]:
df

   emp_id     name  age   join_date gender  city
0     301   Farhan   29  2021-05-14      M   Del
1     302    Gauri   34  03/11/2020      F   Mum
2     303    Imran   41  2019-07-01      M  Bang
3     304    Jyoti   25  22-01-2022      F   Del
4     305    Kunal   38  2018-12-19      M   Che
5     306     Lata   45  2020-06-30      F   Mum
6     307   Manish   31  15/09/2021      M  Bang
7     308    Nisha   27  2022-02-10      F   Del
8     309    Omkar   50  2017-03-25      M   Che
9     310  Pallavi   36  2019-11-11      F  Bang

In [4]:
df["join_date"] = pd.to_datetime(df["join_date"], format="mixed", dayfirst=True)

In [5]:
df

   emp_id     name  age  join_date gender  city
0     301   Farhan   29 2021-05-14      M   Del
1     302    Gauri   34 2020-11-03      F   Mum
2     303    Imran   41 2019-07-01      M  Bang
3     304    Jyoti   25 2022-01-22      F   Del
4     305    Kunal   38 2018-12-19      M   Che
5     306     Lata   45 2020-06-30      F   Mum
6     307   Manish   31 2021-09-15      M  Bang
7     308    Nisha   27 2022-02-10      F   Del
8     309    Omkar   50 2017-03-25      M   Che
9     310  Pallavi   36 2019-11-11      F  Bang

In [7]:
print(df["join_date"].dtype)

datetime64[ns]

In [8]:
df["gender"]

0    M
1    F
2    M
3    F
4    M
5    F
6    M
7    F
8    M
9    F
Name: gender, dtype: object

In [9]:
gender = {"M":"Male","F":"Female"}
df["gender"] = df["gender"].map(gender)

In [10]:
df["gender"]

0      Male
1    Female
2      Male
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: gender, dtype: object

In [11]:
df

   emp_id     name  age  join_date  gender  city
0     301   Farhan   29 2021-05-14    Male   Del
1     302    Gauri   34 2020-11-03  Female   Mum
2     303    Imran   41 2019-07-01    Male  Bang
3     304    Jyoti   25 2022-01-22  Female   Del
4     305    Kunal   38 2018-12-19    Male   Che
5     306     Lata   45 2020-06-30  Female   Mum
6     307   Manish   31 2021-09-15    Male  Bang
7     308    Nisha   27 2022-02-10  Female   Del
8     309    Omkar   50 2017-03-25    Male   Che
9     310  Pallavi   36 2019-11-11  Female  Bang

In [12]:
cities = {"Del":"Delhi","Mum":"Mumbai","Che":"Chennai","Bang":"Bangalore"}
df["city"] = df["city"].map(cities)

In [13]:
df

   emp_id     name  age  join_date  gender       city
0     301   Farhan   29 2021-05-14    Male      Delhi
1     302    Gauri   34 2020-11-03  Female     Mumbai
2     303    Imran   41 2019-07-01    Male  Bangalore
3     304    Jyoti   25 2022-01-22  Female      Delhi
4     305    Kunal   38 2018-12-19    Male    Chennai
5     306     Lata   45 2020-06-30  Female     Mumbai
6     307   Manish   31 2021-09-15    Male  Bangalore
7     308    Nisha   27 2022-02-10  Female      Delhi
8     309    Omkar   50 2017-03-25    Male    Chennai
9     310  Pallavi   36 2019-11-11  Female  Bangalore