In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("1_missing_values.csv").copy()

In [4]:
df.isnull()

   student_id   name  subject  score  attendance
0       False  False    False  False       False
1       False  False    False   True       False
2       False  False    False  False        True
3       False  False    False   True       False
4       False  False    False  False       False
5       False  False    False   True        True
6       False  False    False  False       False
7       False  False    False  False        True
8       False  False    False  False       False
9       False  False    False   True       False

In [5]:
df.isnull().sum()

student_id    0
name          0
subject       0
score         4
attendance    3
dtype: int64

In [6]:
df.dropna()

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
4           5   Rohan  Science   54.0        95.0
6           7  Aditya  English   88.0        84.0
8           9  Vivaan     Math   72.0        90.0

In [8]:
df.dropna(axis=1)

   student_id    name  subject
0           1   Aarav     Math
1           2    Diya  Science
2           3   Kabir     Math
3           4   Meera  English
4           5   Rohan  Science
5           6    Isha     Math
6           7  Aditya  English
7           8   Priya  Science
8           9  Vivaan     Math
9          10    Sara  English

In [9]:
df

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
1           2    Diya  Science    NaN        88.0
2           3   Kabir     Math   65.0         NaN
3           4   Meera  English    NaN        79.0
4           5   Rohan  Science   54.0        95.0
5           6    Isha     Math    NaN         NaN
6           7  Aditya  English   88.0        84.0
7           8   Priya  Science   90.0         NaN
8           9  Vivaan     Math   72.0        90.0
9          10    Sara  English    NaN        81.0

In [12]:
df["score"] = df["score"].fillna(0)

In [18]:
df["attendance"]= df["attendance"].fillna(df["attendance"].mean())

In [19]:
df

   student_id    name  subject  score  attendance
0           1   Aarav     Math   78.0        92.0
1           2    Diya  Science    0.0        88.0
2           3   Kabir     Math   65.0        87.0
3           4   Meera  English    0.0        79.0
4           5   Rohan  Science   54.0        95.0
5           6    Isha     Math    0.0        87.0
6           7  Aditya  English   88.0        84.0
7           8   Priya  Science   90.0        87.0
8           9  Vivaan     Math   72.0        90.0
9          10    Sara  English    0.0        81.0

In [24]:
df1 = pd.DataFrame({"Name":["Teja","Raju","danush","spidy"]})
df1

     Name
0    Teja
1    Raju
2  danush
3   spidy

In [31]:
df1=pd.DataFrame({"Name":["Teja","Raju","danush","spidy","Teja","danush"]})

In [32]:
df1.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [33]:
df1.drop_duplicates()

     Name
0    Teja
1    Raju
2  danush
3   spidy

In [35]:
df1=pd.DataFrame({"Name":["Teja","Raju","danush","spidy","Teja","danush"],
                 "Age":[21,33,43,12,21,33]})

In [36]:
df1

     Name  Age
0    Teja   21
1    Raju   33
2  danush   43
3   spidy   12
4    Teja   21
5  danush   33

In [37]:
df1.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [38]:
df1.drop_duplicates(subset=["Name","Age"])

     Name  Age
0    Teja   21
1    Raju   33
2  danush   43
3   spidy   12
5  danush   33

In [41]:
df2 = pd.read_csv("1745500125912-data.csv").copy()

In [42]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [43]:
df2["Actor"].str.split(" ")

0        [Shah, Rukh, Khan]
1            [Salman, Khan]
2             [Aamir, Khan]
3          [Ranbir, Kapoor]
4          [Ranveer, Singh]
5     [Ayushmann, Khurrana]
6          [Rajkummar, Rao]
7         [Hrithik, Roshan]
8           [Akshay, Kumar]
9          [Kartik, Aaryan]
10          [Varun, Dhawan]
11         [Vicky, Kaushal]
Name: Actor, dtype: object

In [51]:
df2["Actor"].str.split(" ").str.join(sep=" ").str.lower()

0         shah rukh khan
1            salman khan
2             aamir khan
3          ranbir kapoor
4          ranveer singh
5     ayushmann khurrana
6          rajkummar rao
7         hrithik roshan
8           akshay kumar
9          kartik aaryan
10          varun dhawan
11         vicky kaushal
Name: Actor, dtype: object

In [54]:
df2["Actor"].str.contains("shah rukh khan",case=False)

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: Actor, dtype: bool

In [56]:
df2["IMDb"].astype(int)

0     7
1     6
2     8
3     5
4     7
5     8
6     7
7     6
8     7
9     5
10    6
11    8
Name: IMDb, dtype: int64

In [5]:
import pandas as pd

df = pd.DataFrame({"date": ["2024-01-15", "2024-02-20", "2024-03-05"]})
print(df.dtypes)

date    object
dtype: object

In [7]:
df["date"] = pd.to_datetime(df["date"])
print(df.dtypes)

date    datetime64[ns]
dtype: object

In [9]:
dff = pd.DataFrame({"birthday" : ["2000-05-10", "1998-11-23", "2001-07-01"]})
print(dff)
print(dff.dtypes)

     birthday
0  2000-05-10
1  1998-11-23
2  2001-07-01
birthday    object
dtype: object

In [10]:
dff["birthday"] = pd.to_datetime(dff["birthday"])
print(dff)
print(dff.dtypes)

    birthday
0 2000-05-10
1 1998-11-23
2 2001-07-01
birthday    datetime64[ns]
dtype: object

In [11]:
df = pd.DataFrame({"date": ["15/01/2024", "20/02/2024", "05/03/2024"]})
df["date"] = pd.to_datetime(df["date"], format="%d/%m/%Y")
print(df)

        date
0 2024-01-15
1 2024-02-20
2 2024-03-05

In [14]:
df = pd.DataFrame({"event_day" : ["March 5, 2024", "April 10, 2024", "July 4, 2024"]})
print(df)
df["event_day"] = pd.to_datetime(df["event_day"] , format="%B %d, %Y")
print(df)

        event_day
0   March 5, 2024
1  April 10, 2024
2    July 4, 2024
   event_day
0 2024-03-05
1 2024-04-10
2 2024-07-04

In [16]:
df = pd.DataFrame({"log_time":["2024-01-15 14:30:00", "2024-02-20 09:05:00", "2024-03-05 23:59:00"]})
print(df)
df["log_time"] = pd.to_datetime(df["log_time"] , format="%Y-%m-%d %H:%M:%S")
print(df)

              log_time
0  2024-01-15 14:30:00
1  2024-02-20 09:05:00
2  2024-03-05 23:59:00
             log_time
0 2024-01-15 14:30:00
1 2024-02-20 09:05:00
2 2024-03-05 23:59:00

In [17]:
df = pd.DataFrame({"date": ["01/02/2024", "03/04/2024"]})

print(pd.to_datetime(df["date"]))                  # assumes MM/DD -> Jan 2, Mar 4
print(pd.to_datetime(df["date"], dayfirst=True))    # assumes DD/MM -> Feb 1, Apr 3

0   2024-01-02
1   2024-03-04
Name: date, dtype: datetime64[ns]
0   2024-02-01
1   2024-04-03
Name: date, dtype: datetime64[ns]

In [20]:
df = pd.DataFrame({"date":["05/06/2024", "12/01/2024", "25/03/2024"]})
print(df)
print(pd.to_datetime(df["date"] , dayfirst=True))

         date
0  05/06/2024
1  12/01/2024
2  25/03/2024
0   2024-06-05
1   2024-01-12
2   2024-03-25
Name: date, dtype: datetime64[ns]

In [21]:
df = pd.DataFrame({"date": ["2024-01-15", "not a date", "2024-03-05", None]})

df["clean"] = pd.to_datetime(df["date"], errors="coerce")
print(df)

         date      clean
0  2024-01-15 2024-01-15
1  not a date        NaT
2  2024-03-05 2024-03-05
3        None        NaT

In [22]:
df = pd.DataFrame({"price": [100, 250, 75]})

def add_tax(x):
    return x * 1.18

df["price_with_tax"] = df["price"].apply(add_tax)
print(df)

   price  price_with_tax
0    100           118.0
1    250           295.0
2     75            88.5

In [26]:
df = pd.DataFrame({"score":[55, 82, 40, 91, 67]})
print(df)

df["grade"] = df["score"].apply(lambda x: "pass" if x>50 else "fail")
print(df)

   score
0     55
1     82
2     40
3     91
4     67
   score grade
0     55  pass
1     82  pass
2     40  fail
3     91  pass
4     67  pass

In [29]:
df = pd.DataFrame({"temp":[-5, 0, 15, 30, 42]})
print(df)
def classify(x):
    if x<=0:
        return "Freezing"
    elif x>=1 and x<=25:
        return "Mild"
    else:
        return "Hot"
df["condition"] = df["temp"].apply(classify)
print(df)

   temp
0    -5
1     0
2    15
3    30
4    42
   temp condition
0    -5  Freezing
1     0  Freezing
2    15      Mild
3    30       Hot
4    42       Hot

In [30]:
df = pd.DataFrame({"grade": ["A", "B", "C"]})

grade_map = {"A": 90, "B": 80, "C": 70}
df["score"] = df["grade"].map(grade_map)
print(df)

  grade  score
0     A     90
1     B     80
2     C     70

In [31]:
df = pd.DataFrame({"grade": ["A", "B", "Z"]})
df["score"] = df["grade"].map(grade_map)
print(df)
# "Z" isn't in the dictionary -> becomes NaN

  grade  score
0     A   90.0
1     B   80.0
2     Z    NaN

In [39]:
df = pd.DataFrame({"day":["Mon", "Tue", "Wed", "Sat", "Sun"]})
print(df)
df["full_day"] = df["day"].map({"Mon":"Monday","Tue":"Tuesday","Wed":"Wednesday","Thu":"Thursday","Fri":"Friday","Sat":"Saturday","Sun":"Sunday"})
print(df)
partial_map = {"Mon":"Monday","Tue":"Tuesday","Wed":"Wednesday","Thu":"Thursday","Fri":"Friday"}
df["full_day2"] = df["day"].map(partial_map)
print(df)

   day
0  Mon
1  Tue
2  Wed
3  Sat
4  Sun
   day   full_day
0  Mon     Monday
1  Tue    Tuesday
2  Wed  Wednesday
3  Sat   Saturday
4  Sun     Sunday
   day   full_day  full_day2
0  Mon     Monday     Monday
1  Tue    Tuesday    Tuesday
2  Wed  Wednesday  Wednesday
3  Sat   Saturday        NaN
4  Sun     Sunday        NaN

In [41]:
df = pd.DataFrame({"grade": ["A", "B", "C", "D"]})

df["grade"] = df["grade"].replace({"A": "Excellent", "B": "Good"})
print(df)
df["grade"] = df["grade"].replace({"C":"Average"})
print(df)

       grade
0  Excellent
1       Good
2          C
3          D
       grade
0  Excellent
1       Good
2    Average
3          D

In [43]:
df = pd.DataFrame({"status":["active", "inactive", "pending", "active", "unknown"]})
print(df)
df["status"] = df["status"].replace({"active":"Active","inactive":"Inactive"})
print(df)

     status
0    active
1  inactive
2   pending
3    active
4   unknown
     status
0    Active
1  Inactive
2   pending
3    Active
4   unknown