In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [3]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
#selecting columns
print(df["total_bill"]) #selecting single column 

print(df[["total_bill","tip"]]) #selecting multiple columns

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [12]:
#selecting rows
df.loc[0] #selecting a single row

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [13]:
df.iloc[0] #selecting a single row by position

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [20]:
df.loc[0, "total_bill"]  #selecting a specific row and column by label

np.float64(16.99)

In [21]:
df.iloc[0 , 0] #selecting a specific row and column by position

np.float64(16.99)

In [28]:
df.loc[0:2,["total_bill","tip"]] #slicing , the last row in inclusive

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50

In [29]:
df.iloc[0:2,0:2]  #slicing , the last row in exclusive

   total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [30]:
#fast accessing a single element
df.at[0,"total_bill"]

np.float64(16.99)

In [31]:
df.iat[0,0]

np.float64(16.99)

In [32]:
#filtering and conditions

In [36]:
df[df["sex"] == "Male"] #getting only male rows

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [39]:
df[df["total_bill"]>30][0:4] #filtering and slicing

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4

In [40]:
#multiple conditions AND OR

In [42]:
df[ ( df["total_bill"]>30 ) & ( df["sex"]== "Male" ) ]

     total_bill    tip   sex smoker   day    time  size
23        39.42   7.58  Male     No   Sat  Dinner     4
39        31.27   5.00  Male     No   Sat  Dinner     3
44        30.40   5.60  Male     No   Sun  Dinner     4
47        32.40   6.00  Male     No   Sun  Dinner     4
56        38.01   3.00  Male    Yes   Sat  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
83        32.68   5.00  Male    Yes  Thur   Lunch     2
95        40.17   4.73  Male    Yes   Fri  Dinner     4
112       38.07   4.00  Male     No   Sun  Dinner     3
141       34.30   6.70  Male     No  Thur   Lunch     6
142       41.19   5.00  Male     No  Thur   Lunch     5
156       48.17   5.00  Male     No   Sun  Dinner     6
167       31.71   4.50  Male     No   Sun  Dinner     4
170       50.81  10.00  Male    Yes   Sat  Dinner     3
173       31.85   3.18  Male    Yes   Sun  Dinner     2
175       32.90   3.11  Male    Yes   Sun  Dinner     2
179       34.63   3.55  Male    Yes   Sun  Dinner     2
180       34.65   3.68  Male    Yes   Sun  Dinner     4
182       45.35   3.50  Male    Yes   Sun  Dinner     3
184       40.55   3.00  Male    Yes   Sun  Dinner     2
187       30.46   2.00  Male    Yes   Sun  Dinner     5
207       38.73   3.00  Male    Yes   Sat  Dinner     4
210       30.06   2.00  Male    Yes   Sat  Dinner     3
212       48.33   9.00  Male     No   Sat  Dinner     4
237       32.83   1.17  Male    Yes   Sat  Dinner     2

In [43]:
df[ (df["total_bill"] > 45 ) | ( df["sex"] == "Male" ) ]

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [44]:
#querying with .query() method

In [47]:
df.query(" total_bill > 30 and time == 'Dinner' ")

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

In [49]:
df.query("day == 'Sun' ")

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [53]:
col = "total_bill"
df.query(f"{col} > 25")

     total_bill    tip     sex smoker   day    time  size
5         25.29   4.71    Male     No   Sun  Dinner     4
7         26.88   3.12    Male     No   Sun  Dinner     4
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
52        34.81   5.20  Female     No   Sun  Dinner     4
54        25.56   4.34    Male     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
90        28.97   3.00    Male    Yes   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
107       25.21   4.29    Male    Yes   Sat  Dinner     2
112       38.07   4.00    Male     No   Sun  Dinner     3
114       25.71   4.00  Female     No   Sun  Dinner     3
116       29.93   5.07    Male     No   Sun  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
173       31.85   3.18    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
187       30.46   2.00    Male    Yes   Sun  Dinner     5
192       28.44   2.56    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
216       28.15   3.00    Male    Yes   Sat  Dinner     5
219       30.14   3.09  Female    Yes   Sat  Dinner     4
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2

In [55]:
col = "day"
df.query(f"{col} == 'Sun' ")

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [56]:
totalbill = 30
df.query("total_bill > @totalbill")

     total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
112       38.07   4.00    Male     No   Sun  Dinner     3
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
173       31.85   3.18    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
187       30.46   2.00    Male    Yes   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
207       38.73   3.00    Male    Yes   Sat  Dinner     4
210       30.06   2.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
219       30.14   3.09  Female    Yes   Sat  Dinner     4
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3