In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_messy.csv")
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [5]:
df["order_id"] #selecting a single column

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
Name: order_id, dtype: int64

In [7]:
df[["order_id","customer","product"] ] #selecting multiple columns

    order_id      customer   product
0       1001    Ravi Kumar    Laptop
1       1002   Sneha Reddy     Mouse
2       1003     Amit Shah  Keyboard
3       1004    Priya Nair    Laptop
4       1005           NaN   Monitor
5       1006    Vikram Rao     Mouse
6       1007   Sneha Reddy     Mouse
7       1008   Anita Desai  Keyboard
8       1009   Rahul Verma    Laptop
9       1010  Kavita Joshi   Monitor
10      1011   Suresh Iyer     Mouse
11      1012    Neha Gupta  Keyboard
12      1013   Rahul Verma    Laptop
13      1014  Anjali Mehta   Monitor
14      1015  Deepak Singh     Mouse

In [10]:
df.loc[0 : 2] #selecting rows

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east

In [11]:
df.loc[0:2,["order_id","customer","product"]]

   order_id     customer   product
0      1001   Ravi Kumar    Laptop
1      1002  Sneha Reddy     Mouse
2      1003    Amit Shah  Keyboard

In [13]:
df.iloc[0:3,0:3]

   order_id     customer   product
0      1001   Ravi Kumar    Laptop
1      1002  Sneha Reddy     Mouse
2      1003    Amit Shah  Keyboard

In [16]:
df.at[0,"customer"]

'Ravi Kumar'

In [17]:
df.iat[0,1]

'Ravi Kumar'

In [18]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [21]:
df[ df["product"]=="Laptop" ]

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South

In [25]:
df[ (df["product"]=="Laptop" )| (df["status"] == "Delivered") ]

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west

In [27]:
df.query("product == 'Laptop'")

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South

In [28]:
df.query("status=='Delivered'")

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west

In [29]:
df.query("product == 'Laptop' and status == 'Delivered' ")

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South