In [3]:
import pandas as pd

In [8]:
dff = pd.read_csv("1745500125912-data.csv")

In [9]:
df = dff.copy()

In [10]:
df.head()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [11]:
df.tail()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     object
 1   Film                  12 non-null     object
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     object
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

In [13]:
df.describe()

              Year  BoxOffice(INR Crore)       IMDb
count    12.000000             12.000000  12.000000
mean   2019.000000            545.666667   6.975000
std       2.215647            528.535942   0.981766
min    2016.000000            111.000000   5.600000
25%    2017.750000            249.750000   6.075000
50%    2018.500000            386.500000   7.000000
75%    2019.750000            570.000000   7.675000
max    2023.000000           2024.000000   8.400000

In [14]:
df.columns

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='object')

In [16]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [17]:
df[["Actor","Film","Year"]]

                 Actor                      Film  Year
0       Shah Rukh Khan                   Pathaan  2023
1          Salman Khan           Tiger Zinda Hai  2017
2           Aamir Khan                    Dangal  2016
3        Ranbir Kapoor                Brahmastra  2022
4        Ranveer Singh                 Padmaavat  2018
5   Ayushmann Khurrana                 Andhadhun  2018
6        Rajkummar Rao                     Stree  2018
7       Hrithik Roshan                       War  2019
8         Akshay Kumar                Good Newwz  2019
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022
10        Varun Dhawan     Badrinath Ki Dulhania  2017
11       Vicky Kaushal  Uri: The Surgical Strike  2019

In [18]:
df[df["Year"]>2020]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [23]:
df.loc[1,["Actor","Film","Year"]]

Actor        Salman Khan
Film     Tiger Zinda Hai
Year                2017
Name: 1, dtype: object

In [25]:
df.iloc[1,[0,1,2]]

Actor        Salman Khan
Film     Tiger Zinda Hai
Year                2017
Name: 1, dtype: object

In [26]:
df.loc[0:3,:]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [27]:
df.iloc[0:3,:]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [28]:
df.query("Actor == 'Aamir Khan'")

        Actor    Film  Year      Genre  BoxOffice(INR Crore)  IMDb
2  Aamir Khan  Dangal  2016  Biography                  2024   8.4

In [29]:
df.query("Year == 2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2