In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_messy.csv").copy()

In [3]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [8]:
print(df.head())
print(df.info())
print(df.describe())

   order_id     customer   product  quantity    price  order_date     status  \
0      1001   Ravi Kumar    Laptop       2.0  $450.00  04/01/2024  Delivered
1      1002  Sneha Reddy     Mouse       5.0   $12.50  04/02/2024  delivered
2      1003    Amit Shah  Keyboard       NaN    25.00  2024-04-02    Pending
3      1004   Priya Nair    Laptop       1.0      450  04/03/2024  DELIVERED
4      1005          NaN   Monitor       3.0   150.00  04/04/2024  Cancelled

  region
0  South
1  North
2   east
3  South
4   West
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    15 non-null     int64
 1   customer    14 non-null     object
 2   product     15 non-null     object
 3   quantity    14 non-null     float64
 4   price       14 non-null     object
 5   order_date  15 non-null     object
 6   status      15 non-null     object
 7   region      15 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB
None
          order_id    quantity
count    15.000000   14.000000
mean   1008.000000   74.142857
std       4.472136  266.204623
min    1001.000000   -1.000000
25%    1004.500000    2.000000
50%    1008.000000    2.500000
75%    1011.500000    4.750000
max    1015.000000  999.000000

In [9]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [13]:
df = df.dropna(subset="customer").copy()
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [14]:
df["product"] = df["product"].str.lower()

In [15]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,laptop,1.0,450,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,mouse,2.0,12.50,04/11/2024,pending,North

In [18]:
df = df[ (df["quantity"]>0 )& (df["quantity"]<30)].copy()

In [41]:
def removestr(x):
    x = str(x)
    if x.startswith("$"):
        x = x.strip("$")
    return float(x )

In [43]:
df["price"] = df["price"].apply(removestr)

In [44]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,450.0,04/01/2024,Delivered,South
1,1002,Sneha Reddy,mouse,5.0,12.5,04/02/2024,delivered,North
3,1004,Priya Nair,laptop,1.0,450.0,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,mouse,5.0,12.5,04/02/2024,delivered,North
7,1008,Anita Desai,keyboard,4.0,25.0,invalid_date,Pending,East
9,1010,Kavita Joshi,monitor,2.0,150.0,04/07/2024,Returned,West
10,1011,Suresh Iyer,mouse,10.0,12.5,04/08/2024,Delivered,North
11,1012,Neha Gupta,keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,laptop,1.0,450.0,04/06/2024,Delivered,South
14,1015,Deepak Singh,mouse,2.0,12.5,04/11/2024,pending,North

In [46]:
df = df.dropna(subset="price").copy()

In [47]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,450.0,04/01/2024,Delivered,South
1,1002,Sneha Reddy,mouse,5.0,12.5,04/02/2024,delivered,North
3,1004,Priya Nair,laptop,1.0,450.0,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,mouse,5.0,12.5,04/02/2024,delivered,North
7,1008,Anita Desai,keyboard,4.0,25.0,invalid_date,Pending,East
9,1010,Kavita Joshi,monitor,2.0,150.0,04/07/2024,Returned,West
10,1011,Suresh Iyer,mouse,10.0,12.5,04/08/2024,Delivered,North
12,1013,Rahul Verma,laptop,1.0,450.0,04/06/2024,Delivered,South
14,1015,Deepak Singh,mouse,2.0,12.5,04/11/2024,pending,North

In [50]:
df["order_date"] = pd.to_datetime(df["order_date"] , format="%d/%m/%Y" , errors="coerce")

In [54]:
df = df.dropna(subset="order_date").copy()

In [55]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,450.0,2024-01-04,Delivered,South
1,1002,Sneha Reddy,mouse,5.0,12.5,2024-02-04,delivered,North
3,1004,Priya Nair,laptop,1.0,450.0,2024-03-04,DELIVERED,South
5,1006,Vikram Rao,mouse,2.0,12.5,2024-04-04,Delivered,North
6,1007,Sneha Reddy,mouse,5.0,12.5,2024-02-04,delivered,North
9,1010,Kavita Joshi,monitor,2.0,150.0,2024-07-04,Returned,West
10,1011,Suresh Iyer,mouse,10.0,12.5,2024-08-04,Delivered,North
12,1013,Rahul Verma,laptop,1.0,450.0,2024-06-04,Delivered,South
14,1015,Deepak Singh,mouse,2.0,12.5,2024-11-04,pending,North

In [58]:
df["status"] = df["status"].str.lower()

In [59]:
df["region"] = df["region"].str.lower()

In [60]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,450.0,2024-01-04,delivered,south
1,1002,Sneha Reddy,mouse,5.0,12.5,2024-02-04,delivered,north
3,1004,Priya Nair,laptop,1.0,450.0,2024-03-04,delivered,south
5,1006,Vikram Rao,mouse,2.0,12.5,2024-04-04,delivered,north
6,1007,Sneha Reddy,mouse,5.0,12.5,2024-02-04,delivered,north
9,1010,Kavita Joshi,monitor,2.0,150.0,2024-07-04,returned,west
10,1011,Suresh Iyer,mouse,10.0,12.5,2024-08-04,delivered,north
12,1013,Rahul Verma,laptop,1.0,450.0,2024-06-04,delivered,south
14,1015,Deepak Singh,mouse,2.0,12.5,2024-11-04,pending,north

In [64]:
df.duplicated(subset=[i for i in df.columns[1:]])

0     False
1     False
3     False
5     False
6      True
9     False
10    False
12    False
14    False
dtype: bool

In [66]:
df = df.drop_duplicates(subset=[i for i in df.columns[1:]]).copy()

In [67]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,laptop,2.0,450.0,2024-01-04,delivered,south
1,1002,Sneha Reddy,mouse,5.0,12.5,2024-02-04,delivered,north
3,1004,Priya Nair,laptop,1.0,450.0,2024-03-04,delivered,south
5,1006,Vikram Rao,mouse,2.0,12.5,2024-04-04,delivered,north
9,1010,Kavita Joshi,monitor,2.0,150.0,2024-07-04,returned,west
10,1011,Suresh Iyer,mouse,10.0,12.5,2024-08-04,delivered,north
12,1013,Rahul Verma,laptop,1.0,450.0,2024-06-04,delivered,south
14,1015,Deepak Singh,mouse,2.0,12.5,2024-11-04,pending,north

In [68]:
df.groupby("product")["price"].max()

product
laptop     450.0
monitor    150.0
mouse       12.5
Name: price, dtype: float64

In [69]:
df.groupby("region")["price"].sum()

region
north      50.0
south    1350.0
west      150.0
Name: price, dtype: float64