In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("regional_sales_raw.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   txn_id          20 non-null     int64
 1   store           20 non-null     object
 2   category        20 non-null     object
 3   item            20 non-null     object
 4   qty             18 non-null     float64
 5   unit_price      20 non-null     int64
 6   txn_date        20 non-null     object
 7   payment_method  20 non-null     object
 8   customer_age    17 non-null     float64
 9   rating          17 non-null     float64
dtypes: float64(3), int64(2), object(5)
memory usage: 1.7+ KB

In [4]:
df.describe()

           txn_id         qty   unit_price  customer_age     rating
count    20.00000   18.000000    20.000000     17.000000  17.000000
mean   5010.50000   57.888889   866.600000     44.000000   4.164706
std       5.91608  234.880417   654.409207     31.110689   0.459539
min    5001.00000    1.000000   -45.000000     -5.000000   3.000000
25%    5005.75000    1.000000   474.000000     29.000000   4.000000
50%    5010.50000    2.000000   650.000000     41.000000   4.200000
75%    5015.25000    3.000000  1499.000000     47.000000   4.500000
max    5020.00000  999.000000  1999.000000    150.000000   4.900000

In [10]:
df["store"] = df["store"].str.strip().str.lower()

In [12]:
df["category"] = df["category"].str.strip().str.lower()

In [14]:
df["payment_method"] = df["payment_method"].str.strip().str.lower()

In [20]:
df = df.drop_duplicates(subset=df.columns.drop("txn_id"))

In [24]:
df["rating"] = df["rating"].fillna(0)

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_9980/2468117227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["rating"] = df["rating"].fillna(0)

In [26]:
df["customer_age"] = df["customer_age"].fillna(df["customer_age"].mean())

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_9980/2759809374.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["customer_age"] = df["customer_age"].fillna(df["customer_age"].mean())

In [28]:
df=df.dropna()

In [30]:
df["txn_date"] = pd.to_datetime(df["txn_date"] , format="mixed", errors="coerce")

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_9980/1248053775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["txn_date"] = pd.to_datetime(df["txn_date"] , format="mixed", errors="coerce")

In [31]:
df

,txn_id,store,category,item,qty,unit_price,txn_date,payment_method,customer_age,rating
0,5001,store a,electronics,Headphones,2.0,1499,2023-11-01,card,28.0,4.5
1,5002,store b,grocery,Rice 5kg,1.0,650,2023-11-01,cash,45.0,0.0
2,5003,store a,electronics,Charger,3.0,499,2023-01-11,card,45.0,3.8
4,5005,store b,grocery,Rice 5kg,1.0,650,2023-11-02,cash,45.0,4.2
6,5007,store d,clothing,Jeans,1.0,1999,2023-11-03,card,-5.0,3.0
7,5008,store c,grocery,Sugar 1kg,4.0,45,2023-11-03,upi,52.0,4.6
8,5009,store a,electronics,Mouse,2.0,399,2023-03-11,cash,45.0,0.0
9,5010,store b,clothing,T-Shirt,5.0,799,2023-11-04,card,29.0,4.9
11,5012,store c,electronics,Charger,1.0,499,2023-11-05,card,150.0,3.5
12,5013,store a,clothing,Jeans,2.0,1999,2023-11-05,cash,33.0,0.0
14,5015,store d,electronics,Mouse,10.0,399,2023-11-06,card,41.0,4.4
15,5016,store c,clothing,T-Shirt,3.0,799,NaT,upi,26.0,4.3
16,5017,store a,grocery,Sugar 1kg,2.0,-45,2023-11-07,cash,38.0,4.0
17,5018,store b,electronics,Headphones,1.0,1499,2023-11-07,card,45.0,4.7
18,5019,store d,clothing,Jeans,999.0,1999,2023-11-08,upi,47.0,3.9
19,5020,store c,grocery,Rice 5kg,2.0,650,2023-11-08,cash,55.0,4.2

In [32]:
df = df[(df["unit_price"]>0) & (df["customer_age"].between(0,100))]

In [33]:
df

,txn_id,store,category,item,qty,unit_price,txn_date,payment_method,customer_age,rating
0,5001,store a,electronics,Headphones,2.0,1499,2023-11-01,card,28.0,4.5
1,5002,store b,grocery,Rice 5kg,1.0,650,2023-11-01,cash,45.0,0.0
2,5003,store a,electronics,Charger,3.0,499,2023-01-11,card,45.0,3.8
4,5005,store b,grocery,Rice 5kg,1.0,650,2023-11-02,cash,45.0,4.2
7,5008,store c,grocery,Sugar 1kg,4.0,45,2023-11-03,upi,52.0,4.6
8,5009,store a,electronics,Mouse,2.0,399,2023-03-11,cash,45.0,0.0
9,5010,store b,clothing,T-Shirt,5.0,799,2023-11-04,card,29.0,4.9
12,5013,store a,clothing,Jeans,2.0,1999,2023-11-05,cash,33.0,0.0
14,5015,store d,electronics,Mouse,10.0,399,2023-11-06,card,41.0,4.4
15,5016,store c,clothing,T-Shirt,3.0,799,NaT,upi,26.0,4.3
17,5018,store b,electronics,Headphones,1.0,1499,2023-11-07,card,45.0,4.7
18,5019,store d,clothing,Jeans,999.0,1999,2023-11-08,upi,47.0,3.9
19,5020,store c,grocery,Rice 5kg,2.0,650,2023-11-08,cash,55.0,4.2