In [1]:
import pandas as pd

In [23]:
df = pd.read_csv("sales_messy.csv")
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [5]:
df.isnull() #checking for null values

    order_id  customer  product  quantity  price  order_date  status  region
0      False     False    False     False  False       False   False   False
1      False     False    False     False  False       False   False   False
2      False     False    False      True  False       False   False   False
3      False     False    False     False  False       False   False   False
4      False      True    False     False  False       False   False   False
5      False     False    False     False  False       False   False   False
6      False     False    False     False  False       False   False   False
7      False     False    False     False  False       False   False   False
8      False     False    False     False  False       False   False   False
9      False     False    False     False  False       False   False   False
10     False     False    False     False  False       False   False   False
11     False     False    False     False   True       False   False   False
12     False     False    False     False  False       False   False   False
13     False     False    False     False  False       False   False   False
14     False     False    False     False  False       False   False   False

In [7]:
df.isnull().sum() #count null values per column

order_id      0
customer      1
product       0
quantity      1
price         1
order_date    0
status        0
region        0
dtype: int64

In [8]:
df.dropna() # drops rows with missing or null values

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [10]:
df.dropna(axis=1) # Drop columns with missing values

    order_id   product    order_date     status region
0       1001    Laptop    04/01/2024  Delivered  South
1       1002     Mouse    04/02/2024  delivered  North
2       1003  Keyboard    2024-04-02    Pending   east
3       1004    Laptop    04/03/2024  DELIVERED  South
4       1005   Monitor    04/04/2024  Cancelled   West
5       1006     Mouse    04/04/2024  Delivered  North
6       1007     Mouse    04/02/2024  delivered  North
7       1008  Keyboard  invalid_date    Pending   East
8       1009    Laptop    04/06/2024  Delivered  south
9       1010   Monitor    04/07/2024   Returned   West
10      1011     Mouse    04/08/2024  Delivered  North
11      1012  Keyboard    04/09/2024    Pending   East
12      1013    Laptop    04/06/2024  Delivered  South
13      1014   Monitor    04/10/2024  Delivered   west
14      1015     Mouse    04/11/2024    pending  North

In [14]:
df["price"].fillna(df.iloc[2,4])

0     $450.00
1      $12.50
2       25.00
3         450
4      150.00
5        12.5
6      $12.50
7          25
8      450.00
9     $150.00
10      12.50
11      25.00
12     450.00
13     150.00
14      12.50
Name: price, dtype: object

In [16]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,Ravi Kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,Amit Shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,Priya Nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,Vikram Rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,Sneha Reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,Anita Desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,Rahul Verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,Kavita Joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,Suresh Iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,Neha Gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,Rahul Verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,Anjali Mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,Deepak Singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [19]:
df["customer"] = df["customer"].str.lower()

In [20]:
df

,order_id,customer,product,quantity,price,order_date,status,region
0,1001,ravi kumar,Laptop,2.0,$450.00,04/01/2024,Delivered,South
1,1002,sneha reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
2,1003,amit shah,Keyboard,NaN,25.00,2024-04-02,Pending,east
3,1004,priya nair,Laptop,1.0,450,04/03/2024,DELIVERED,South
4,1005,NaN,Monitor,3.0,150.00,04/04/2024,Cancelled,West
5,1006,vikram rao,Mouse,2.0,12.5,04/04/2024,Delivered,North
6,1007,sneha reddy,Mouse,5.0,$12.50,04/02/2024,delivered,North
7,1008,anita desai,Keyboard,4.0,25,invalid_date,Pending,East
8,1009,rahul verma,Laptop,-1.0,450.00,04/06/2024,Delivered,south
9,1010,kavita joshi,Monitor,2.0,$150.00,04/07/2024,Returned,West
10,1011,suresh iyer,Mouse,10.0,12.50,04/08/2024,Delivered,North
11,1012,neha gupta,Keyboard,3.0,NaN,04/09/2024,Pending,East
12,1013,rahul verma,Laptop,1.0,450.00,04/06/2024,Delivered,South
13,1014,anjali mehta,Monitor,999.0,150.00,04/10/2024,Delivered,west
14,1015,deepak singh,Mouse,2.0,12.50,04/11/2024,pending,North

In [22]:
df["product"].str.contains("Laptop" ,case=False)

0      True
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
Name: product, dtype: bool