In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [5]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [6]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [7]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [8]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [9]:
df["Total_salary_dept"] = df.groupby("Department")["Salary"].transform("sum")

In [11]:
df.groupby("Gender")["Salary"].sum()

Gender
F    343
M    330
Name: Salary, dtype: int64

In [14]:
df.groupby("Department")["Salary"].agg(avg_salary="mean" , max_salary="max" , min_salary="min")

            avg_salary  max_salary  min_salary
Department
HR                87.5          90          85
IT                81.5          85          78
Marketing         90.0          92          88
Sales             77.5          80          75

In [15]:
df

  Department Team Gender  Salary  Age   JoinDate  Total_salary_dept
0         HR    A      M      85   23 2020-01-10                175
1         HR    A      F      90   25 2020-02-15                175
2         IT    B      M      78   30 2021-03-20                163
3         IT    B      F      85   22 2021-04-10                163
4  Marketing    C      M      92   28 2020-05-30                180
5  Marketing    C      F      88   26 2020-06-25                180
6      Sales    D      M      75   21 2021-07-15                155
7      Sales    D      F      80   27 2021-08-01                155

In [18]:
df.groupby("Department").filter(lambda x:x["Salary"].sum()>175)

  Department Team Gender  Salary  Age   JoinDate  Total_salary_dept
4  Marketing    C      M      92   28 2020-05-30                180
5  Marketing    C      F      88   26 2020-06-25                180