In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("gym_bookings_raw.csv")

In [32]:
df = df_raw

In [6]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating
0,8001,rohit sharma,Downtown,Aditi,Yoga,500,60.0,2024-04-01,gold,4.5
1,8002,priya patel,uptown,Rahul,HIIT,700,45.0,2024-04-01,Gold,4.2
2,8003,rohit sharma,Downtown,Aditi,Yoga,500,60.0,2024-04-01,gold,4.5
3,8004,sameer khan,Downtown,Aditi,Yoga,500,55.0,04/02/2024,silver,4.0
4,8005,neha verma,Uptown,Rahul,hiit,700,NaN,2024-04-02,gold,NaN
5,8006,aman gupta,eastside,Kiran,Pilates,600,50.0,2024-04-02,Silver,4.3
6,8007,priya patel,Uptown,Rahul,HIIT,700,45.0,2024-04-01,gold,4.2
7,8008,divya singh,Downtown,aditi,yoga,510,62.0,2024-04-03,Gold,4.6
8,8009,karan mehta,Eastside,Kiran,pilates,600,48.0,03-04-2024,silver,4.1
9,8010,sana iqbal,uptown,Rahul,HIIT,720,-20.0,2024-04-04,Gold,3.9
10,8011,vivek rao,Downtown,Aditi,Yoga,505,58.0,2024-04-04,silver,4.4
11,8012,farah ali,Eastside,kiran,Pilates,610,52.0,2024-04-05,Silver,4.2
12,8013,ishaan kapoor,Uptown,rahul,HIIT,700,300.0,2024-04-05,gold,4.0
13,8014,meera joshi,downtown,Aditi,Yoga,500,60.0,2024-04-06,Gold,4.7
14,8015,aman gupta,Eastside,Kiran,pilates,600,50.0,2024-04-02,silver,4.3
15,8016,kabir nair,Uptown,Rahul,hiit,-700,42.0,2024-04-06,gold,3.8
16,8017,ritu chawla,Eastside,Kiran,Pilates,615,49.0,invalid_date,Silver,4.5
17,8018,nikhil bansal,Downtown,aditi,Yoga,500,60.0,2024-04-07,gold,4.6
18,8019,alia sheikh,uptown,Rahul,HIIT,710,44.0,2024-04-07,Gold,4.1
19,8020,ritu chawla,eastside,kiran,pilates,615,49.0,2024-04-07,silver,4.5

In [33]:
df["member_name"] =  df["member_name"].str.strip().str.lower()

In [34]:
df["branch"] = df["branch"].str.strip().str.lower()

In [35]:
df["trainer"] = df["trainer"].str.strip().str.lower()

In [36]:
df["class_type"] = df["class_type"].str.strip().str.lower()

In [37]:
df["membership_type"] = df["membership_type"].str.strip().str.lower()

In [38]:
df["member_rating"] = df["member_rating"].fillna(df["member_rating"].mean())

In [39]:
df["booking_date"] = pd.to_datetime(df["booking_date"] , format="mixed" , errors="coerce")

In [40]:
df["session_minutes"] = df["session_minutes"].fillna(df["session_minutes"].mean())

In [41]:
df["session_minutes"] = df["session_minutes"].astype(int)

In [42]:
df = df[ df["session_minutes"] > 0 ]

In [23]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
2,8003,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
3,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000
4,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211
5,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
6,8007,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
7,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000
8,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000
10,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000
11,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000
12,8013,ishaan kapoor,uptown,rahul,hiit,700,300,2024-04-05,gold,4.000000
13,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000
14,8015,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
15,8016,kabir nair,uptown,rahul,hiit,-700,42,2024-04-06,gold,3.800000
16,8017,ritu chawla,eastside,kiran,pilates,615,49,NaT,silver,4.500000
17,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000
18,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000
19,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000

In [43]:
df = df.dropna()

In [25]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
2,8003,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
3,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000
4,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211
5,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
6,8007,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
7,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000
8,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000
10,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000
11,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000
12,8013,ishaan kapoor,uptown,rahul,hiit,700,300,2024-04-05,gold,4.000000
13,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000
14,8015,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
15,8016,kabir nair,uptown,rahul,hiit,-700,42,2024-04-06,gold,3.800000
17,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000
18,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000
19,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000

In [44]:
df = df[ df["session_minutes"] < 180 ]

In [28]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
2,8003,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
3,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000
4,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211
5,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
6,8007,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
7,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000
8,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000
10,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000
11,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000
13,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000
14,8015,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
15,8016,kabir nair,uptown,rahul,hiit,-700,42,2024-04-06,gold,3.800000
17,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000
18,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000
19,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000

In [45]:
df.duplicated(df.columns.drop("booking_id"))

0     False
1     False
2      True
3     False
4     False
5     False
6      True
7     False
8     False
10    False
11    False
13    False
14     True
15    False
17    False
18    False
19    False
dtype: bool

In [47]:
df = df.drop_duplicates(df.columns.drop("booking_id"))

In [51]:
df = df.reset_index(drop=True)

In [53]:
df = df[ df["fee"] > 0 ]

In [54]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000
2,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000
3,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211
4,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000
5,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000
6,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000
7,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000
8,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000
9,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000
11,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000
12,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000
13,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000

In [55]:
#finding average fee per branch
df.groupby("branch")["fee"].mean()

branch
downtown    502.500000
eastside    606.250000
uptown      703.333333
Name: fee, dtype: float64

In [56]:
#finding average rating per branch and class type
df.groupby(["branch","class_type"])["member_rating"].mean()

branch    class_type
downtown  yoga          4.466667
eastside  pilates       4.275000
uptown    hiit          4.194737
Name: member_rating, dtype: float64

In [57]:
df.groupby("trainer")["fee"].agg(["mean","max","min"])

               mean  max  min
trainer
aditi    502.500000  510  500
kiran    606.250000  615  600
rahul    703.333333  710  700

In [60]:
df["branch_avg_fee"] = df.groupby("branch")["fee"].transform("mean")

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_15328/4201780188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["branch_avg_fee"] = df.groupby("branch")["fee"].transform("mean")

In [62]:
df["fee_vs_branch_avg"] = df["fee"] - df["branch_avg_fee"]

/var/folders/yg/v2xb54j57hv9plgd_h_vzdzr0000gn/T/ipykernel_15328/4246203952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["fee_vs_branch_avg"] = df["fee"] - df["branch_avg_fee"]

In [63]:
df

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating,branch_avg_fee,fee_vs_branch_avg
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000,502.500000,-2.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000,703.333333,-3.333333
2,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000,502.500000,-2.500000
3,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211,703.333333,-3.333333
4,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000,606.250000,-6.250000
5,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000,502.500000,7.500000
6,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000,606.250000,-6.250000
7,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000,502.500000,2.500000
8,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000,606.250000,3.750000
9,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000,502.500000,-2.500000
11,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000,502.500000,-2.500000
12,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000,703.333333,6.666667
13,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000,606.250000,8.750000

In [64]:
df_filtered = df.groupby("branch").filter(lambda x: x["member_rating"].mean() > 4.2)

,booking_id,member_name,branch,trainer,class_type,fee,session_minutes,booking_date,membership_type,member_rating,branch_avg_fee,fee_vs_branch_avg
0,8001,rohit sharma,downtown,aditi,yoga,500,60,2024-04-01,gold,4.500000,502.500000,-2.500000
1,8002,priya patel,uptown,rahul,hiit,700,45,2024-04-01,gold,4.200000,703.333333,-3.333333
2,8004,sameer khan,downtown,aditi,yoga,500,55,2024-04-02,silver,4.000000,502.500000,-2.500000
3,8005,neha verma,uptown,rahul,hiit,700,61,2024-04-02,gold,4.284211,703.333333,-3.333333
4,8006,aman gupta,eastside,kiran,pilates,600,50,2024-04-02,silver,4.300000,606.250000,-6.250000
5,8008,divya singh,downtown,aditi,yoga,510,62,2024-04-03,gold,4.600000,502.500000,7.500000
6,8009,karan mehta,eastside,kiran,pilates,600,48,2024-03-04,silver,4.100000,606.250000,-6.250000
7,8011,vivek rao,downtown,aditi,yoga,505,58,2024-04-04,silver,4.400000,502.500000,2.500000
8,8012,farah ali,eastside,kiran,pilates,610,52,2024-04-05,silver,4.200000,606.250000,3.750000
9,8014,meera joshi,downtown,aditi,yoga,500,60,2024-04-06,gold,4.700000,502.500000,-2.500000
11,8018,nikhil bansal,downtown,aditi,yoga,500,60,2024-04-07,gold,4.600000,502.500000,-2.500000
12,8019,alia sheikh,uptown,rahul,hiit,710,44,2024-04-07,gold,4.100000,703.333333,6.666667
13,8020,ritu chawla,eastside,kiran,pilates,615,49,2024-04-07,silver,4.500000,606.250000,8.750000